name = "SparseDiskFEM"
uuid = "0223b3cf-36df-47a1-a98c-d61ab4cb4c7a"
authors = ["john.papad "]
version = "0.0.1"

[deps]
AnnuliOrthogonalPolynomials = "de1797fd-24c3-4035-91a2-b52aecdcfb01"
ClassicalOrthogonalPolynomials = "b30e2e7b-c4ee-47da-9d5f-2c5c27239acd"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Elliptic = "b305315f-e792-5b7a-8f41-49f472929428"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MultivariateOrthogonalPolynomials = "4f6956fd-4f93-5457-9149-7bfc4b2ce06d"
PiecewiseOrthogonalPolynomials = "4461d12d-4663-4550-8580-cb764c85e20f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
RadialPiecewisePolynomials = "7dab568b-3cf7-4f91-a977-b4631dfca174"
SemiclassicalOrthogonalPolynomials = "291c01f3-23f6-4eb6-aeb0-063a639b53f2"

[compat]
AnnuliOrthogonalPolynomials = "=0.0.4"
ClassicalOrthogonalPolynomials = "=0.12.4"
DelimitedFiles = "1.9.1"
Elliptic = "=1.0.1"
ForwardDiff = "0.10.36"
LaTeXStrings = "1.3.1"
MultivariateOrthogonalPolynomials = "=0.6.4"
PiecewiseOrthogonalPolynomials = "=0.4.1"
Plots = "1.39"
PyPlot = "=2.11.2"
RadialPiecewisePolynomials = "=0.1.1"
SemiclassicalOrthogonalPolynomials = "=0.5.5"
